[package]
name = "vino"
version = "0.1.1"
edition = "2024"
description = "A visual novel engine in the future."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Myc123abc/vino"

[dependencies]
vino-graphics = { path = "../vino-graphics" }